//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.JP.DataHub.ApiWeb.Infrastructure.Resources.OpenIdUserRepository {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.JP.DataHub.ApiWeb.Infrastructure.Resources.OpenIdUserRepository.Response" +
                            "s", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;odata.metadata&quot;: &quot;https://graph.windows.net/datahubjp.onmicrosoft.com/$metadata#directoryObjects&quot;,
        ///  &quot;value&quot;: [
        ///    {
        ///      &quot;odata.type&quot;: &quot;Microsoft.DirectoryServices.Application&quot;,
        ///      &quot;objectType&quot;: &quot;Application&quot;,
        ///      &quot;objectId&quot;: &quot;34fde61a-688f-440a-a516-9e3d17826f81&quot;,
        ///      &quot;deletionTimestamp&quot;: null,
        ///      &quot;acceptMappedClaims&quot;: null,
        ///      &quot;addIns&quot;: [],
        ///      &quot;appId&quot;: &quot;7861b5c5-ab91-4a29-b0d6-60f110e87a27&quot;,
        ///      &quot;appRoles&quot;: [],
        ///      &quot;availableToOtherTenants&quot;: false,
        ///      &quot;displayNa [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetApplicationResponse {
            get {
                return ResourceManager.GetString("GetApplicationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;odata.metadata&quot;: &quot;https://graph.windows.net/datahubjp.onmicrosoft.com/$metadata#directoryObjects&quot;,
        ///  &quot;value&quot;: [
        ///    {
        ///      &quot;odata.type&quot;: &quot;Microsoft.DirectoryServices.ExtensionProperty&quot;,
        ///      &quot;objectType&quot;: &quot;ExtensionProperty&quot;,
        ///      &quot;objectId&quot;: &quot;a02b8360-01d6-452b-b786-3b149b2475c8&quot;,
        ///      &quot;deletionTimestamp&quot;: null,
        ///      &quot;appDisplayName&quot;: &quot;&quot;,
        ///      &quot;name&quot;: &quot;extension_12345678_SystemId&quot;,
        ///      &quot;dataType&quot;: &quot;String&quot;,
        ///      &quot;isSyncedFromOnPremises&quot;: false,
        ///      &quot;targetObjects&quot;: [
        ///        &quot;U [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetPropertyNameResponse {
            get {
                return ResourceManager.GetString("GetPropertyNameResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;value&quot;: [
        ///    {
        ///      &quot;odata.type&quot;: &quot;Microsoft.DirectoryServices.User&quot;,
        ///      &quot;objectType&quot;: &quot;User&quot;,
        ///      &quot;objectId&quot;: &quot;d2d03b3b-6d5c-46a8-9ebd-965faad4b46f&quot;,
        ///      &quot;deletionTimestamp&quot;: null,
        ///      &quot;accountEnabled&quot;: true,
        ///      &quot;ageGroup&quot;: null,
        ///      &quot;assignedLicenses&quot;: [],
        ///      &quot;assignedPlans&quot;: [],
        ///      &quot;city&quot;: null,
        ///      &quot;companyName&quot;: null,
        ///      &quot;consentProvidedForMinor&quot;: null,
        ///      &quot;country&quot;: null,
        ///      &quot;createdDateTime&quot;: &quot;2019-02-18T10:00:33Z&quot;,
        ///      &quot;creationType&quot;: &quot;LocalAcc [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetUserResponse {
            get {
                return ResourceManager.GetString("GetUserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;odata.error&quot;: {
        ///    &quot;code&quot;: &quot;Request_BadRequest&quot;,
        ///    &quot;message&quot;: {
        ///      &quot;lang&quot;: &quot;en&quot;,
        ///      &quot;value&quot;: &quot;One or more properties contains invalid values.&quot;
        ///    },
        ///    &quot;requestId&quot;: &quot;84c1865e-0542-4ef2-93b1-73ae04f56b11&quot;,
        ///    &quot;date&quot;: &quot;2019-02-20T02:23:58&quot;
        ///  }
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenIdUserErrorResponse {
            get {
                return ResourceManager.GetString("OpenIdUserErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;odata.metadata&quot;: &quot;https://graph.windows.net/datahubjp.onmicrosoft.com/$metadata#directoryObjects/@Element&quot;,
        ///  &quot;odata.type&quot;: &quot;Microsoft.DirectoryServices.User&quot;,
        ///  &quot;objectType&quot;: &quot;User&quot;,
        ///  &quot;objectId&quot;: &quot;d2d03b3b-6d5c-46a8-9ebd-965faad4b46f&quot;,
        ///  &quot;deletionTimestamp&quot;: null,
        ///  &quot;accountEnabled&quot;: true,
        ///  &quot;ageGroup&quot;: null,
        ///  &quot;assignedLicenses&quot;: [],
        ///  &quot;assignedPlans&quot;: [],
        ///  &quot;city&quot;: null,
        ///  &quot;companyName&quot;: null,
        ///  &quot;consentProvidedForMinor&quot;: null,
        ///  &quot;country&quot;: null,
        ///  &quot;createdDateTime&quot;: null,
        ///  &quot;creatio [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegisterUserResponse {
            get {
                return ResourceManager.GetString("RegisterUserResponse", resourceCulture);
            }
        }
    }
}
