version: "3"

services:
  webserver:
    container_name: sdgs_webserver
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.sdgs.conf:/etc/nginx/conf.d/sdgs.conf

  app:
    container_name: sdgs_app
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini

  db:
    container_name: sdgs_db
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - sdgs_db_data:/var/lib/mysql/

volumes:
  sdgs_db_data:
