<?php

define('APPLICATION_STATUS_ANSWER', 0);
define('APPLICATION_STATUS_APPROVED', 1);
define('APPLICATION_STATUS_REJECTED', 2);
define('APPLICATION_STATUS_SCORED', 3);
define('PAGINATE_DEFAULT', 10);
define('FARM_QUESTIONS_START', 1);
define('TOTAL_FARM_QUESTIONS', 20);
define('RESTAURANT_QUESTIONS_START', 1);
define('TOTAL_RESTAURANT_QUESTIONS', 8);
define('FILE_MARK', 1);
define('FILE_CERTIFICATE', 2);
define('MAX_SCORE_FARM_APPLICATION', 100);
