
// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Information`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=tcp:jpdatahubdev.database.windows.net,1433;Initial Catalog=InformationSqlServer;Persist Security Info=False;User ID=agri;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using JP.DataHub.Com.Validations.Attributes;

namespace JP.DataHub.Infrastructure.Database.Information
{
    public static class DatabaseConst
    {
        public const string DATABASE = "Information";
        public const string TABLE_INFORMATION = "Information";

        public static readonly string COLUMN_INFORMATION_INFORMATION_ID = "information_id";
        public static readonly string COLUMN_INFORMATION_TITLE = "title";
        public static readonly string COLUMN_INFORMATION_DETAIL = "detail";
        public static readonly string COLUMN_INFORMATION_DATE = "date";
        public static readonly string COLUMN_INFORMATION_REG_DATE = "reg_date";
        public static readonly string COLUMN_INFORMATION_REG_USERNAME = "reg_username";
        public static readonly string COLUMN_INFORMATION_UPD_DATE = "upd_date";
        public static readonly string COLUMN_INFORMATION_UPD_USERNAME = "upd_username";
        public static readonly string COLUMN_INFORMATION_IS_ACTIVE = "is_active";
        public static readonly string COLUMN_INFORMATION_IS_VISIBLE_API = "is_visible_api";
        public static readonly string COLUMN_INFORMATION_IS_VISIBLE_ADMIN = "is_visible_admin";
    }

    public enum Tables
    {
        Information,
    }

    public enum InformationInformation
    {
        [DbMap("Information","Information","information_id")]
        information_id,
        [DbMap("Information","Information","title")]
        title,
        [DbMap("Information","Information","detail")]
        detail,
        [DbMap("Information","Information","date")]
        date,
        [DbMap("Information","Information","reg_date")]
        reg_date,
        [DbMap("Information","Information","reg_username")]
        reg_username,
        [DbMap("Information","Information","upd_date")]
        upd_date,
        [DbMap("Information","Information","upd_username")]
        upd_username,
        [DbMap("Information","Information","is_active")]
        is_active,
        [DbMap("Information","Information","is_visible_api")]
        is_visible_api,
        [DbMap("Information","Information","is_visible_admin")]
        is_visible_admin,
    }


    /// <summary>
    /// A class which represents the Information table.
    /// </summary>
	[Table("Information")]
	public partial class DB_Information
	{
		[Key]
		public virtual Guid information_id { get; set; }
		[MaxLength(512)]
		public virtual string title { get; set; }
		[MaxLength(1000)]
		public virtual string detail { get; set; }
		[MaxLength(50)]
		public virtual string date { get; set; }
		[Dapper.IgnoreUpdate]
		public virtual DateTime reg_date { get; set; }
		[Dapper.IgnoreUpdate]
		[MaxLength(260)]
		public virtual string reg_username { get; set; }
		public virtual DateTime upd_date { get; set; }
		[MaxLength(260)]
		public virtual string upd_username { get; set; }
		public virtual bool is_active { get; set; }
		public virtual bool is_visible_api { get; set; }
		public virtual bool is_visible_admin { get; set; }
	}

}
