
// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Trail`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=tcp:jpdatahubdev.database.windows.net,1433;Initial Catalog=TrailSqlServer;Persist Security Info=False;User ID=agri;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using JP.DataHub.Com.Validations.Attributes;

namespace JP.DataHub.Infrastructure.Database.Trail
{
    public static class DatabaseConst
    {
        public const string DATABASE = "Trail";
        public const string TABLE_ADMIN = "Admin";
        public const string TABLE_STAFF = "Staff";
        public const string TABLE_TRAIL = "Trail";
        public const string TABLE_TRAILTYPE = "TrailType";
        public const string TABLE_VENDOR = "Vendor";

        public static readonly string COLUMN_ADMIN_TRAIL_ID = "trail_id";
        public static readonly string COLUMN_ADMIN_SCREEN = "screen";
        public static readonly string COLUMN_ADMIN_OPERATION = "operation";
        public static readonly string COLUMN_ADMIN_CONTOLLER_CLASS_NAME = "contoller_class_name";
        public static readonly string COLUMN_ADMIN_ACTION_METHOD_NAME = "action_method_name";
        public static readonly string COLUMN_ADMIN_OPEN_ID = "open_id";
        public static readonly string COLUMN_ADMIN_VENDOR_ID = "vendor_id";
        public static readonly string COLUMN_ADMIN_IP_ADDRESS = "ip_address";
        public static readonly string COLUMN_ADMIN_USER_AGENT = "user_agent";
        public static readonly string COLUMN_ADMIN_URL = "url";
        public static readonly string COLUMN_ADMIN_HTTP_METHOD_TYPE = "http_method_type";
        public static readonly string COLUMN_ADMIN_HTTP_STATUS_CODE = "http_status_code";
        public static readonly string COLUMN_ADMIN_METHOD_PARAMETER = "method_parameter";
        public static readonly string COLUMN_ADMIN_METHOD_RESULT = "method_result";
        public static readonly string COLUMN_ADMIN_REG_DATE = "reg_date";
        public static readonly string COLUMN_STAFF_STAFF_ID = "staff_id";
        public static readonly string COLUMN_STAFF_ACCOUNT = "account";
        public static readonly string COLUMN_STAFF_VENDOR_ID = "vendor_id";
        public static readonly string COLUMN_STAFF_UPD_DATE = "upd_date";
        public static readonly string COLUMN_STAFF_UPD_USERNAME = "upd_username";
        public static readonly string COLUMN_STAFF_IS_ACTIVE = "is_active";
        public static readonly string COLUMN_STAFF_EMAIL_ADDRESS = "email_address";
        public static readonly string COLUMN_TRAIL_TRAIL_ID = "trail_id";
        public static readonly string COLUMN_TRAIL_TRAIL_TYPE_CD = "trail_type_cd";
        public static readonly string COLUMN_TRAIL_RESULT = "result";
        public static readonly string COLUMN_TRAIL_DETAIL = "detail";
        public static readonly string COLUMN_TRAIL_REG_DATE = "reg_date";
        public static readonly string COLUMN_TRAILTYPE_TRAIL_TYPE_CD = "trail_type_cd";
        public static readonly string COLUMN_TRAILTYPE_TRAIL_TYPE_NAME = "trail_type_name";
        public static readonly string COLUMN_TRAILTYPE_REG_DATE = "reg_date";
        public static readonly string COLUMN_TRAILTYPE_REG_USERNAME = "reg_username";
        public static readonly string COLUMN_TRAILTYPE_UPD_DATE = "upd_date";
        public static readonly string COLUMN_TRAILTYPE_UPD_USERNAME = "upd_username";
        public static readonly string COLUMN_VENDOR_VENDOR_ID = "vendor_id";
        public static readonly string COLUMN_VENDOR_VENDOR_NAME = "vendor_name";
        public static readonly string COLUMN_VENDOR_IS_ENABLE = "is_enable";
        public static readonly string COLUMN_VENDOR_UPD_DATE = "upd_date";
        public static readonly string COLUMN_VENDOR_UPD_USERNAME = "upd_username";
        public static readonly string COLUMN_VENDOR_IS_ACTIVE = "is_active";
    }

    public enum Tables
    {
        Admin,
        Staff,
        Trail,
        TrailType,
        Vendor,
    }

    public enum TrailAdmin
    {
        [DbMap("Trail","Admin","trail_id")]
        trail_id,
        [DbMap("Trail","Admin","screen")]
        screen,
        [DbMap("Trail","Admin","operation")]
        operation,
        [DbMap("Trail","Admin","contoller_class_name")]
        contoller_class_name,
        [DbMap("Trail","Admin","action_method_name")]
        action_method_name,
        [DbMap("Trail","Admin","open_id")]
        open_id,
        [DbMap("Trail","Admin","vendor_id")]
        vendor_id,
        [DbMap("Trail","Admin","ip_address")]
        ip_address,
        [DbMap("Trail","Admin","user_agent")]
        user_agent,
        [DbMap("Trail","Admin","url")]
        url,
        [DbMap("Trail","Admin","http_method_type")]
        http_method_type,
        [DbMap("Trail","Admin","http_status_code")]
        http_status_code,
        [DbMap("Trail","Admin","method_parameter")]
        method_parameter,
        [DbMap("Trail","Admin","method_result")]
        method_result,
        [DbMap("Trail","Admin","reg_date")]
        reg_date,
    }
    public enum TrailStaff
    {
        [DbMap("Trail","Staff","staff_id")]
        staff_id,
        [DbMap("Trail","Staff","account")]
        account,
        [DbMap("Trail","Staff","vendor_id")]
        vendor_id,
        [DbMap("Trail","Staff","upd_date")]
        upd_date,
        [DbMap("Trail","Staff","upd_username")]
        upd_username,
        [DbMap("Trail","Staff","is_active")]
        is_active,
        [DbMap("Trail","Staff","email_address")]
        email_address,
    }
    public enum TrailTrail
    {
        [DbMap("Trail","Trail","trail_id")]
        trail_id,
        [DbMap("Trail","Trail","trail_type_cd")]
        trail_type_cd,
        [DbMap("Trail","Trail","result")]
        result,
        [DbMap("Trail","Trail","detail")]
        detail,
        [DbMap("Trail","Trail","reg_date")]
        reg_date,
    }
    public enum TrailTrailType
    {
        [DbMap("Trail","TrailType","trail_type_cd")]
        trail_type_cd,
        [DbMap("Trail","TrailType","trail_type_name")]
        trail_type_name,
        [DbMap("Trail","TrailType","reg_date")]
        reg_date,
        [DbMap("Trail","TrailType","reg_username")]
        reg_username,
        [DbMap("Trail","TrailType","upd_date")]
        upd_date,
        [DbMap("Trail","TrailType","upd_username")]
        upd_username,
    }
    public enum TrailVendor
    {
        [DbMap("Trail","Vendor","vendor_id")]
        vendor_id,
        [DbMap("Trail","Vendor","vendor_name")]
        vendor_name,
        [DbMap("Trail","Vendor","is_enable")]
        is_enable,
        [DbMap("Trail","Vendor","upd_date")]
        upd_date,
        [DbMap("Trail","Vendor","upd_username")]
        upd_username,
        [DbMap("Trail","Vendor","is_active")]
        is_active,
    }


    /// <summary>
    /// A class which represents the Admin table.
    /// </summary>
	[Table("Admin")]
	public partial class DB_Admin
	{
		[Key]
		public virtual Guid trail_id { get; set; }
		[MaxLength(256)]
		public virtual string screen { get; set; }
		[MaxLength(260)]
		public virtual string operation { get; set; }
		[MaxLength(500)]
		public virtual string contoller_class_name { get; set; }
		[MaxLength(500)]
		public virtual string action_method_name { get; set; }
		public virtual Guid? open_id { get; set; }
		public virtual Guid? vendor_id { get; set; }
		[MaxLength(70)]
		public virtual string ip_address { get; set; }
		[MaxLength(1000)]
		public virtual string user_agent { get; set; }
		[MaxLength(4000)]
		public virtual string url { get; set; }
		[MaxLength(30)]
		public virtual string http_method_type { get; set; }
		public virtual int? http_status_code { get; set; }
		[MaxLength(1000)]
		public virtual string method_parameter { get; set; }
		[MaxLength(1000)]
		public virtual string method_result { get; set; }
		[Dapper.IgnoreUpdate]
		public virtual DateTime reg_date { get; set; }
	}


    /// <summary>
    /// A class which represents the Staff table.
    /// </summary>
	[Table("Staff")]
	public partial class DB_Staff
	{
		[Key]
		public virtual Guid staff_id { get; set; }
		[MaxLength(100)]
		public virtual string account { get; set; }
		public virtual Guid vendor_id { get; set; }
		public virtual DateTime upd_date { get; set; }
		[MaxLength(260)]
		public virtual string upd_username { get; set; }
		public virtual bool is_active { get; set; }
		[MaxLength(256)]
		public virtual string email_address { get; set; }
	}


    /// <summary>
    /// A class which represents the Trail table.
    /// </summary>
	[Table("Trail")]
	public partial class DB_Trail
	{
		[Key]
		public virtual Guid trail_id { get; set; }
		[MaxLength(3)]
		public virtual string trail_type_cd { get; set; }
		public virtual bool result { get; set; }
		[MaxLength(1000)]
		public virtual string detail { get; set; }
		[Dapper.IgnoreUpdate]
		public virtual DateTime reg_date { get; set; }
		public virtual DB_TrailType DB_TrailType { get; set; }
	}


    /// <summary>
    /// A class which represents the TrailType table.
    /// </summary>
	[Table("TrailType")]
	public partial class DB_TrailType
	{
		[Key]
		[MaxLength(3)]
		public virtual string trail_type_cd { get; set; }
		[MaxLength(30)]
		public virtual string trail_type_name { get; set; }
		[Dapper.IgnoreUpdate]
		public virtual DateTime reg_date { get; set; }
		[Dapper.IgnoreUpdate]
		[MaxLength(260)]
		public virtual string reg_username { get; set; }
		public virtual DateTime upd_date { get; set; }
		[MaxLength(260)]
		public virtual string upd_username { get; set; }
		public virtual IEnumerable<DB_Trail> Trail { get; set; }
	}


    /// <summary>
    /// A class which represents the Vendor table.
    /// </summary>
	[Table("Vendor")]
	public partial class DB_Vendor
	{
		[Key]
		public virtual Guid vendor_id { get; set; }
		[MaxLength(260)]
		public virtual string vendor_name { get; set; }
		public virtual bool is_enable { get; set; }
		public virtual DateTime upd_date { get; set; }
		[MaxLength(260)]
		public virtual string upd_username { get; set; }
		public virtual bool is_active { get; set; }
	}

}
