//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JP.DataHub.SmartFoodChainAOP.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmartFoodChainAOPMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmartFoodChainAOPMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JP.DataHub.SmartFoodChainAOP.Resources.SmartFoodChainAOPMessages", typeof(SmartFoodChainAOPMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ユーザーが複数グループに所属しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100400_detail {
            get {
                return ResourceManager.GetString("E100400_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なメンバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100400_title {
            get {
                return ResourceManager.GetString("E100400_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ代表者が設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100401_detail {
            get {
                return ResourceManager.GetString("E100401_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なグループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100401_title {
            get {
                return ResourceManager.GetString("E100401_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   どのグループにも所属していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100402_detail {
            get {
                return ResourceManager.GetString("E100402_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所属グループがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100402_title {
            get {
                return ResourceManager.GetString("E100402_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたグループは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100403_detail {
            get {
                return ResourceManager.GetString("E100403_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存在しないグループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100403_title {
            get {
                return ResourceManager.GetString("E100403_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ代表者ではないため削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100404_detail {
            get {
                return ResourceManager.GetString("E100404_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100404_title {
            get {
                return ResourceManager.GetString("E100404_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストボディを変換できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100405_detail {
            get {
                return ResourceManager.GetString("E100405_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なデータ形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100405_title {
            get {
                return ResourceManager.GetString("E100405_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約枠アカウントの残数がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100406_detail {
            get {
                return ResourceManager.GetString("E100406_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約枠アカウントを取得できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100406_title {
            get {
                return ResourceManager.GetString("E100406_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約枠アカウントの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100407_detail {
            get {
                return ResourceManager.GetString("E100407_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約枠アカウントを取得できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100407_title {
            get {
                return ResourceManager.GetString("E100407_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   代表者は変更できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100408_detail {
            get {
                return ResourceManager.GetString("E100408_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100408_title {
            get {
                return ResourceManager.GetString("E100408_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたグループは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100409_detail {
            get {
                return ResourceManager.GetString("E100409_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存在しないグループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100409_title {
            get {
                return ResourceManager.GetString("E100409_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループの更新権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100410_detail {
            get {
                return ResourceManager.GetString("E100410_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループを更新できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100410_title {
            get {
                return ResourceManager.GetString("E100410_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループの管理者が設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100411_detail {
            get {
                return ResourceManager.GetString("E100411_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なグループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100411_title {
            get {
                return ResourceManager.GetString("E100411_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループの管理者はメンバーに含まれている必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100412_detail {
            get {
                return ResourceManager.GetString("E100412_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なグループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E100412_title {
            get {
                return ResourceManager.GetString("E100412_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   appパラメータを確認し適切なパラメータを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101400_detail {
            get {
                return ResourceManager.GetString("E101400_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   appパラメータが指定されていないか形式が不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101400_title {
            get {
                return ResourceManager.GetString("E101400_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applicationを提供している管理者にApplicationが登録されているか確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101401_detail {
            get {
                return ResourceManager.GetString("E101401_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   appパラメータで指定したApplicationが存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101401_title {
            get {
                return ResourceManager.GetString("E101401_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIの呼び出し形式を確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101402_detail {
            get {
                return ResourceManager.GetString("E101402_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applicationリソースの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101402_title {
            get {
                return ResourceManager.GetString("E101402_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご利用になるにはApplicationにユーザーを登録する必要があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101403_detail {
            get {
                return ResourceManager.GetString("E101403_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーには認可されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101403_title {
            get {
                return ResourceManager.GetString("E101403_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIの呼び出し形式を確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101404_detail {
            get {
                return ResourceManager.GetString("E101404_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ApplicationUserリソースの取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101404_title {
            get {
                return ResourceManager.GetString("E101404_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIの呼び出し形式を確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101405_detail {
            get {
                return ResourceManager.GetString("E101405_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roleリソースの取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101405_title {
            get {
                return ResourceManager.GetString("E101405_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定したアプリケーションが存在しないか、管理者ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101406_detail {
            get {
                return ResourceManager.GetString("E101406_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存在しないアプリケーション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101406_title {
            get {
                return ResourceManager.GetString("E101406_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenId認証が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101407_detail {
            get {
                return ResourceManager.GetString("E101407_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なリクエスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101407_title {
            get {
                return ResourceManager.GetString("E101407_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションの管理者ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101408_detail {
            get {
                return ResourceManager.GetString("E101408_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションなし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E101408_title {
            get {
                return ResourceManager.GetString("E101408_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102401_detail {
            get {
                return ResourceManager.GetString("E102401_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102401_title {
            get {
                return ResourceManager.GetString("E102401_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストボディがJsonに変換できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102402_detail {
            get {
                return ResourceManager.GetString("E102402_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストボディの形式が正しくありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102402_title {
            get {
                return ResourceManager.GetString("E102402_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductCodeがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102403_detail {
            get {
                return ResourceManager.GetString("E102403_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102403_title {
            get {
                return ResourceManager.GetString("E102403_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAS判定が行われていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102404_detail {
            get {
                return ResourceManager.GetString("E102404_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAS判定結果が不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102404_title {
            get {
                return ResourceManager.GetString("E102404_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAS判定の基準を満たしていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102405_detail {
            get {
                return ResourceManager.GetString("E102405_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAS判定結果が不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102405_title {
            get {
                return ResourceManager.GetString("E102405_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取り扱いできない商品コードです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102406_detail {
            get {
                return ResourceManager.GetString("E102406_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの形式が不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102406_title {
            get {
                return ResourceManager.GetString("E102406_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glnがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102407_detail {
            get {
                return ResourceManager.GetString("E102407_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102407_title {
            get {
                return ResourceManager.GetString("E102407_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102408_detail {
            get {
                return ResourceManager.GetString("E102408_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102408_title {
            get {
                return ResourceManager.GetString("E102408_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に合致するデータがありませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102409_detail {
            get {
                return ResourceManager.GetString("E102409_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データがありませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102409_title {
            get {
                return ResourceManager.GetString("E102409_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ文字列がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102410_detail {
            get {
                return ResourceManager.GetString("E102410_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ文字列が正しくありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102410_title {
            get {
                return ResourceManager.GetString("E102410_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductCodeに合致した商品情報が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102411_detail {
            get {
                return ResourceManager.GetString("E102411_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品情報がみつかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102411_title {
            get {
                return ResourceManager.GetString("E102411_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品に対するJAS判定基準が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102412_detail {
            get {
                return ResourceManager.GetString("E102412_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JAS判定基準がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102412_title {
            get {
                return ResourceManager.GetString("E102412_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductCode,Glnコードからセンサーデータを取得しましたが、センサーデータが1件もありませんでした。よってJAS判定は出来ませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102413_detail {
            get {
                return ResourceManager.GetString("E102413_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センサーデータがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102413_title {
            get {
                return ResourceManager.GetString("E102413_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷データが取得できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102415_detail {
            get {
                return ResourceManager.GetString("E102415_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷データがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102415_title {
            get {
                return ResourceManager.GetString("E102415_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された印刷枚数が、印刷可能な枚数を超えています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102416_detail {
            get {
                return ResourceManager.GetString("E102416_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷可能枚数を超えています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102416_title {
            get {
                return ResourceManager.GetString("E102416_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   arrivalIdがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102417_detail {
            get {
                return ResourceManager.GetString("E102417_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102417_title {
            get {
                return ResourceManager.GetString("E102417_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入荷処理が正しく処理できていないか、何らかの影響でトレーサビリティ情報が取得できません。よってJAS判定は行えません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102418_detail {
            get {
                return ResourceManager.GetString("E102418_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入出荷情報が取得できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E102418_title {
            get {
                return ResourceManager.GetString("E102418_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストボディを変換できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103400_detail {
            get {
                return ResourceManager.GetString("E103400_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なデータ形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103400_title {
            get {
                return ResourceManager.GetString("E103400_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録済みのセンサーデバイスです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103401_detail {
            get {
                return ResourceManager.GetString("E103401_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録済みのセンサーデバイス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103401_title {
            get {
                return ResourceManager.GetString("E103401_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当するセンサーが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103402_detail {
            get {
                return ResourceManager.GetString("E103402_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なセンサー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103402_title {
            get {
                return ResourceManager.GetString("E103402_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ文字列がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103403_detail {
            get {
                return ResourceManager.GetString("E103403_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ文字列が正しくありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103403_title {
            get {
                return ResourceManager.GetString("E103403_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductCodeがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103404_detail {
            get {
                return ResourceManager.GetString("E103404_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103404_title {
            get {
                return ResourceManager.GetString("E103404_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ArrivalIdがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103405_detail {
            get {
                return ResourceManager.GetString("E103405_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103405_title {
            get {
                return ResourceManager.GetString("E103405_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの集計が行われていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103406_detail {
            get {
                return ResourceManager.GetString("E103406_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103406_title {
            get {
                return ResourceManager.GetString("E103406_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが登録されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103407_detail {
            get {
                return ResourceManager.GetString("E103407_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103407_title {
            get {
                return ResourceManager.GetString("E103407_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeが不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103408_detail {
            get {
                return ResourceManager.GetString("E103408_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目が不正です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103408_title {
            get {
                return ResourceManager.GetString("E103408_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データストリームを登録する場合、センサーIDおよびセンサー群を指定する必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103409_detail {
            get {
                return ResourceManager.GetString("E103409_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センサーIDまたはセンサー群が未指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103409_title {
            get {
                return ResourceManager.GetString("E103409_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未登録のセンサーデバイスです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103410_detail {
            get {
                return ResourceManager.GetString("E103410_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未登録のセンサーデバイス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103410_title {
            get {
                return ResourceManager.GetString("E103410_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録済みのセンサー群です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103411_detail {
            get {
                return ResourceManager.GetString("E103411_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録済みのセンサー群 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103411_title {
            get {
                return ResourceManager.GetString("E103411_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたセンサーに設定されている測定項目が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103412_detail {
            get {
                return ResourceManager.GetString("E103412_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたセンサーの設定が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103412_title {
            get {
                return ResourceManager.GetString("E103412_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたセンサーに設定されている測定単位が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103413_detail {
            get {
                return ResourceManager.GetString("E103413_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたセンサーの設定が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103413_title {
            get {
                return ResourceManager.GetString("E103413_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103501_detail {
            get {
                return ResourceManager.GetString("E103501_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103501_title {
            get {
                return ResourceManager.GetString("E103501_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103502_detail {
            get {
                return ResourceManager.GetString("E103502_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E103502_title {
            get {
                return ResourceManager.GetString("E103502_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductCodeがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104400_detail {
            get {
                return ResourceManager.GetString("E104400_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104400_title {
            get {
                return ResourceManager.GetString("E104400_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Glnがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104401_detail {
            get {
                return ResourceManager.GetString("E104401_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104401_title {
            get {
                return ResourceManager.GetString("E104401_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104402_detail {
            get {
                return ResourceManager.GetString("E104402_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104402_title {
            get {
                return ResourceManager.GetString("E104402_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に合致するデータがありませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104403_detail {
            get {
                return ResourceManager.GetString("E104403_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104403_title {
            get {
                return ResourceManager.GetString("E104403_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが一致しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104404_detail {
            get {
                return ResourceManager.GetString("E104404_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なパスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104404_title {
            get {
                return ResourceManager.GetString("E104404_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたProductCodeは、既に登録されています。Updateを使用してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104405_detail {
            get {
                return ResourceManager.GetString("E104405_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductCode重複 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104405_title {
            get {
                return ResourceManager.GetString("E104405_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductCodeを指定して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104406_detail {
            get {
                return ResourceManager.GetString("E104406_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProductCodeを指定して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104406_title {
            get {
                return ResourceManager.GetString("E104406_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X-Passwordを指定して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104407_detail {
            get {
                return ResourceManager.GetString("E104407_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X-Passwordを指定して下さい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104407_title {
            get {
                return ResourceManager.GetString("E104407_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたProductCodeは、Updateはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104408_detail {
            get {
                return ResourceManager.GetString("E104408_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたProductCodeは、Updateはできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104408_title {
            get {
                return ResourceManager.GetString("E104408_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたProductCodeは見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104409_detail {
            get {
                return ResourceManager.GetString("E104409_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたProductCodeは見つかりませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E104409_title {
            get {
                return ResourceManager.GetString("E104409_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileIdがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E105400_detail {
            get {
                return ResourceManager.GetString("E105400_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E105400_title {
            get {
                return ResourceManager.GetString("E105400_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ文字列がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106402_detail {
            get {
                return ResourceManager.GetString("E106402_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ文字列が正しくありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106402_title {
            get {
                return ResourceManager.GetString("E106402_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShipmentSensorIdがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106403_detail {
            get {
                return ResourceManager.GetString("E106403_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106403_title {
            get {
                return ResourceManager.GetString("E106403_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LastArrivalIdがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106404_detail {
            get {
                return ResourceManager.GetString("E106404_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106404_title {
            get {
                return ResourceManager.GetString("E106404_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたShipmentSensorIdは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106405_detail {
            get {
                return ResourceManager.GetString("E106405_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なパラメータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106405_title {
            get {
                return ResourceManager.GetString("E106405_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたLastArrivalIdは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106406_detail {
            get {
                return ResourceManager.GetString("E106406_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なパラメータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106406_title {
            get {
                return ResourceManager.GetString("E106406_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたShipmentSensorは測定開始されていないか、すでに測定終了されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106408_detail {
            get {
                return ResourceManager.GetString("E106408_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なパラメータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106408_title {
            get {
                return ResourceManager.GetString("E106408_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106501_detail {
            get {
                return ResourceManager.GetString("E106501_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106501_title {
            get {
                return ResourceManager.GetString("E106501_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShipmentSensorの更新に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106507_detail {
            get {
                return ResourceManager.GetString("E106507_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E106507_title {
            get {
                return ResourceManager.GetString("E106507_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   申請IDが指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107401_detail {
            get {
                return ResourceManager.GetString("E107401_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107401_title {
            get {
                return ResourceManager.GetString("E107401_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された申請は存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107402_detail {
            get {
                return ResourceManager.GetString("E107402_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107402_title {
            get {
                return ResourceManager.GetString("E107402_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたCompanyIdは存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107403_detail {
            get {
                return ResourceManager.GetString("E107403_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なパラメータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107403_title {
            get {
                return ResourceManager.GetString("E107403_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   申請の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107501_detail {
            get {
                return ResourceManager.GetString("E107501_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107501_title {
            get {
                return ResourceManager.GetString("E107501_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107502_detail {
            get {
                return ResourceManager.GetString("E107502_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E107502_title {
            get {
                return ResourceManager.GetString("E107502_title", resourceCulture);
            }
        }
    }
}
