//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JP.DataHub.Api.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DynamicApiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DynamicApiMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JP.DataHub.Api.Core.Resources.DynamicApiMessages", typeof(DynamicApiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AccessControl認証が失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccessControlAuthFailed {
            get {
                return ResourceManager.GetString("AccessControlAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTTPヘッダー：X-AccessBeyondVendorKeyに正しいアクセスコントロールの値を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccessControlAuthFailed_Detail {
            get {
                return ResourceManager.GetString("AccessControlAuthFailed_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理者認証が失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdminAuthFailed {
            get {
                return ResourceManager.GetString("AdminAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTTPヘッダー：X-Adminに正しい管理者認証用のキーワードを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AdminAuthFailed_Detail {
            get {
                return ResourceManager.GetString("AdminAuthFailed_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数の例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AggregateException {
            get {
                return ResourceManager.GetString("AggregateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部サーバーエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnInternalServerErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnInternalServerErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共有が許可されていないOpenIDが指定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnOpenIDWasSpecifiedThatIsNotAllowedToBeShared {
            get {
                return ResourceManager.GetString("AnOpenIDWasSpecifiedThatIsNotAllowedToBeShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIの例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiException {
            get {
                return ResourceManager.GetString("ApiException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API IPフィルタの例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string APIIPFilter {
            get {
                return ResourceManager.GetString("APIIPFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ArgumentNull例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AsyncApi NotEnd例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AsyncApiNotEndException {
            get {
                return ResourceManager.GetString("AsyncApiNotEndException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AsyncApi結果NOTFOUND例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AsyncApiResultNotFoundException {
            get {
                return ResourceManager.GetString("AsyncApiResultNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非同期APIの実行中に予期せぬエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AsyncDynamicApiError {
            get {
                return ResourceManager.GetString("AsyncDynamicApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添付ファイルとブロックチェーン間の不一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_AttachFile_Mismatch {
            get {
                return ResourceManager.GetString("BlockchainValidate_AttachFile_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックチェーンと添付ファイルに記録された値が合致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_AttachFile_Mismatch_Detail {
            get {
                return ResourceManager.GetString("BlockchainValidate_AttachFile_Mismatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックチェーンで添付ファイルハッシュが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_AttachFile_NoBlockchainHash {
            get {
                return ResourceManager.GetString("BlockchainValidate_AttachFile_NoBlockchainHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックチェーン上に指定されたIDの添付ファイルのハッシュ値が記録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_AttachFile_NoBlockchainHash_Detail {
            get {
                return ResourceManager.GetString("BlockchainValidate_AttachFile_NoBlockchainHash_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添付ファイルリポジトリに見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_AttachFile_NoSource {
            get {
                return ResourceManager.GetString("BlockchainValidate_AttachFile_NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリ上に指定されたIDの添付ファイルのデータが記録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_AttachFile_NoSource_Detail {
            get {
                return ResourceManager.GetString("BlockchainValidate_AttachFile_NoSource_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドキュメントの履歴は無効です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_DocumentHistory_Disable {
            get {
                return ResourceManager.GetString("BlockchainValidate_DocumentHistory_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DynamicApiの履歴の機能が無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_DocumentHistory_Disable_Detail {
            get {
                return ResourceManager.GetString("BlockchainValidate_DocumentHistory_Disable_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   specifedバージョンが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_DocumentHistory_VersionNotFound {
            get {
                return ResourceManager.GetString("BlockchainValidate_DocumentHistory_VersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたバージョンの履歴が存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_DocumentHistory_VersionNotFound_Detail {
            get {
                return ResourceManager.GetString("BlockchainValidate_DocumentHistory_VersionNotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリとブロックチェーン間の不一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_Mismatch {
            get {
                return ResourceManager.GetString("BlockchainValidate_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックチェーンとレポジトリに記録された値が合致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_Mismatch_Detail {
            get {
                return ResourceManager.GetString("BlockchainValidate_Mismatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックチェーンに見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_NoBlockchainHash {
            get {
                return ResourceManager.GetString("BlockchainValidate_NoBlockchainHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックチェーン上に指定されたIDのデータが記録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_NoBlockchainHash_Detail {
            get {
                return ResourceManager.GetString("BlockchainValidate_NoBlockchainHash_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリ内に見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_NoSource {
            get {
                return ResourceManager.GetString("BlockchainValidate_NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリ上に指定されたIDのデータが記録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockchainValidate_NoSource_Detail {
            get {
                return ResourceManager.GetString("BlockchainValidate_NoSource_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストがブロックされました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockedRequestedContentTypeOrFileTypeByList {
            get {
                return ResourceManager.GetString("BlockedRequestedContentTypeOrFileTypeByList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストのコンテントタイプかファイルタイプが、リストによりブロックされました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlockedRequestedContentTypeOrFileTypeByList_Detail {
            get {
                return ResourceManager.GetString("BlockedRequestedContentTypeOrFileTypeByList_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsContainerDynamicSeparationが設定されている場合はX-UserResourceSharingの設定は行えません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CannotSetX_UserResourceSharingWhenIsContainerDynamicSeparationIsSet {
            get {
                return ResourceManager.GetString("CannotSetX-UserResourceSharingWhenIsContainerDynamicSeparationIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部から内部コールを呼び出すことはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CantCallInternalCallsFromOutside {
            get {
                return ResourceManager.GetString("CantCallInternalCallsFromOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認定アプリケーションのデータはありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CertifiedApplicationNotFound {
            get {
                return ResourceManager.GetString("CertifiedApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に該当する認定アプリケーションのデータはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CertifiedApplicationNotFound_Detail {
            get {
                return ResourceManager.GetString("CertifiedApplicationNotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クライアント証明書認証が必要です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCertificateAuthenticationRequired {
            get {
                return ResourceManager.GetString("ClientCertificateAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クライアント証明書を設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCertificateAuthenticationRequired_Detail {
            get {
                return ResourceManager.GetString("ClientCertificateAuthenticationRequired_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効期限切れのクライアント証明書です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCertificateExpired {
            get {
                return ResourceManager.GetString("ClientCertificateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効期限内のクライアント証明書を設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCertificateExpired_Detail {
            get {
                return ResourceManager.GetString("ClientCertificateExpired_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クライアント証明書が見つからないか、ベンダーまたはシステムが利用できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCertificateNotFoundOrVendorSystemUnusable {
            get {
                return ResourceManager.GetString("ClientCertificateNotFoundOrVendorSystemUnusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効なクライアント証明書を設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientCertificateNotFoundOrVendorSystemUnusable_Detail {
            get {
                return ResourceManager.GetString("ClientCertificateNotFoundOrVendorSystemUnusable_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClientIdが見つからないか、ベンダーまたはシステムが使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientIdNotFoundOrVendorSystemUnusable {
            get {
                return ResourceManager.GetString("ClientIdNotFoundOrVendorSystemUnusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベンダーシステム認証用のアクセストークンを取得し直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientIdNotFoundOrVendorSystemUnusable_Detail {
            get {
                return ResourceManager.GetString("ClientIdNotFoundOrVendorSystemUnusable_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動的Container分離用リポジトリを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContainerDynamicSeparationRepositoryNotFound {
            get {
                return ResourceManager.GetString("ContainerDynamicSeparationRepositoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   依存設定が依存なしの場合は動的Conainer分離を使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContainerDynamicSeparationRequiredDependency {
            get {
                return ResourceManager.GetString("ContainerDynamicSeparationRequiredDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このAPIは、CSVをサポートしていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CsvParseFailed {
            get {
                return ResourceManager.GetString("CsvParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ暗号化エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataEncryptionError {
            get {
                return ResourceManager.GetString("DataEncryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共通鍵が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataEncryptionError_CommonKeyNotFound {
            get {
                return ResourceManager.GetString("DataEncryptionError_CommonKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの復号に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataEncryptionError_DecryptionFailed {
            get {
                return ResourceManager.GetString("DataEncryptionError_DecryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが既に登録されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("DataIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ提供でないためこのAPIは呼び出せません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefinedInVendorNotUsedFlag {
            get {
                return ResourceManager.GetString("DefinedInVendorNotUsedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自社で定義したリソースは、データ提供を設定しなければなりません。ベンダー設定を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefinedInVendorNotUsedFlag_Detail {
            get {
                return ResourceManager.GetString("DefinedInVendorNotUsedFlag_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ利用でないためこのAPIは呼び出せません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefinedOtherVendorNotUsedFlag {
            get {
                return ResourceManager.GetString("DefinedOtherVendorNotUsedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他社が定義したリソースは、データ利用を設定しなければなりません。ベンダー設定を確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefinedOtherVendorNotUsedFlag_Detail {
            get {
                return ResourceManager.GetString("DefinedOtherVendorNotUsedFlag_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除が正常に行われました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteWasSuccessful {
            get {
                return ResourceManager.GetString("DeleteWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文書が削除されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DocumentHasBeenDeleted {
            get {
                return ResourceManager.GetString("DocumentHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新対象のデータが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoesNotExistDataToBeUpdatedIs {
            get {
                return ResourceManager.GetString("DoesNotExistDataToBeUpdatedIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新対象のデータが存在しません。対象のデータはすでに削除された可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoesNotExistDataToBeUpdatedIs_Detail {
            get {
                return ResourceManager.GetString("DoesNotExistDataToBeUpdatedIs_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DUMMY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dummy {
            get {
                return ResourceManager.GetString("Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DUMMY_DETAIL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dummy_Detail {
            get {
                return ResourceManager.GetString("Dummy_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部サーバーエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXCEPTION_DETAIL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exception_Detail {
            get {
                return ResourceManager.GetString("Exception_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部サーバーエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExceptionOccured {
            get {
                return ResourceManager.GetString("ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントは既に使用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExistStaffAccount {
            get {
                return ResourceManager.GetString("ExistStaffAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部添付ファイルのエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalAttachiFileError {
            get {
                return ResourceManager.GetString("ExternalAttachiFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部データソースへの接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalAttachiFileError_ConnectionFailed {
            get {
                return ResourceManager.GetString("ExternalAttachiFileError_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   履歴機能が有効なAPIでは外部添付ファイルを利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalAttachiFileError_DocumentHistoryUnsupported {
            get {
                return ResourceManager.GetString("ExternalAttachiFileError_DocumentHistoryUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部添付ファイルのファイル情報が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalAttachiFileError_FileInfoMissing {
            get {
                return ResourceManager.GetString("ExternalAttachiFileError_FileInfoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部データソースに指定されたファイルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalAttachiFileError_FileNotFound {
            get {
                return ResourceManager.GetString("ExternalAttachiFileError_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部添付ファイルのファイル情報が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalAttachiFileError_InvalidFileInfo {
            get {
                return ResourceManager.GetString("ExternalAttachiFileError_InvalidFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部添付ファイルはアップロードの必要はありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExternalAttachiFileError_UnnecessaryUpload {
            get {
                return ResourceManager.GetString("ExternalAttachiFileError_UnnecessaryUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DriveOut透過APIで失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedWithDriveOutTransparentAPI {
            get {
                return ResourceManager.GetString("FailedWithDriveOutTransparentAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DriveOut透過APIの処理で、履歴情報が取得できませんでした。履歴が存在しないdocumentの可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedWithDriveOutTransparentAPI_Detail {
            get {
                return ResourceManager.GetString("FailedWithDriveOutTransparentAPI_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileIDが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileIdIsInvalid {
            get {
                return ResourceManager.GetString("FileIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileId設定は不要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileIdNoSettingRequired {
            get {
                return ResourceManager.GetString("FileIdNoSettingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileIDは必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileIdRequired {
            get {
                return ResourceManager.GetString("FileIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileIDを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileIdRequired_Detail {
            get {
                return ResourceManager.GetString("FileIdRequired_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fileは必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileIsRequired {
            get {
                return ResourceManager.GetString("FileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部キーの例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ForeignKeyException {
            get {
                return ResourceManager.GetString("ForeignKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FromNotFoundQuery {
            get {
                return ResourceManager.GetString("FromNotFoundQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定義されているGateway先URLに誤りがある可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GatewayURLDefinedError {
            get {
                return ResourceManager.GetString("GatewayURLDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ名が不正です。モデルのrootプロパティ名にシステムで定義済みのキーワードが指定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HasDefinedKeywordDataSchemaException {
            get {
                return ResourceManager.GetString("HasDefinedKeywordDataSchemaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   履歴データが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HistoryDataNotFound {
            get {
                return ResourceManager.GetString("HistoryDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   履歴データが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HistoryDatNotFound {
            get {
                return ResourceManager.GetString("HistoryDatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Httpメソッドタイプが一致しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HttpMethodTypeDoesNotMatch {
            get {
                return ResourceManager.GetString("HttpMethodTypeDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストされたHttpメソッドタイプはサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HttpMethodTypeDoesNotMatch_Detail {
            get {
                return ResourceManager.GetString("HttpMethodTypeDoesNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストされたHttpメソッドタイプはサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HttpMethodTypeDoesNotSupport {
            get {
                return ResourceManager.GetString("HttpMethodTypeDoesNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Http応答例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HttpResponseException {
            get {
                return ResourceManager.GetString("HttpResponseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   idが一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IdDoesNotMatch {
            get {
                return ResourceManager.GetString("IdDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDが必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IdIsRequired {
            get {
                return ResourceManager.GetString("IdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ODataによる検索を行いましたがデータがありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IMadeASearchByODataDidNotHaveTheData {
            get {
                return ResourceManager.GetString("IMadeASearchByODataDidNotHaveTheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アカウントのフォーマットが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidAccountFormatException {
            get {
                return ResourceManager.GetString("InvalidAccountFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブルの指定方法が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidApiQuerySql_ResourceIdSpecified {
            get {
                return ResourceManager.GetString("InvalidApiQuerySql_ResourceIdSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT句に不正な値が指定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidApiQuerySql_SelectInvalidColumn {
            get {
                return ResourceManager.GetString("InvalidApiQuerySql_SelectInvalidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたテーブルの結合は許可されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidApiQuerySql_TableJoinNotAllowed {
            get {
                return ResourceManager.GetString("InvalidApiQuerySql_TableJoinNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたテーブルが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidApiQuerySql_TableNotFound {
            get {
                return ResourceManager.GetString("InvalidApiQuerySql_TableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結合先として指定されたテーブルが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidApiQuerySql_TableToJoinNotFound {
            get {
                return ResourceManager.GetString("InvalidApiQuerySql_TableToJoinNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添付ファイルのファイル名が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidAttachFileName {
            get {
                return ResourceManager.GetString("InvalidAttachFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なキャスト例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidCastException {
            get {
                return ResourceManager.GetString("InvalidCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なMethodType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidMethodType {
            get {
                return ResourceManager.GetString("InvalidMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AgreeDescriptionが必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidResourceAgreement {
            get {
                return ResourceManager.GetString("InvalidResourceAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   規約の同意を有効化する場合はAgreeDescriptionが必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidResourceAgreement_Detail {
            get {
                return ResourceManager.GetString("InvalidResourceAgreement_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新対象のデータが不正です。オブジェクトではなく配列が指定されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidTypeExpectedObject_ButGotArray {
            get {
                return ResourceManager.GetString("InvalidTypeExpectedObject_ButGotArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なX-Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidXVersion {
            get {
                return ResourceManager.GetString("InvalidXVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル結合が不可能なリポジトリタイプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvaliOtherResourceSqlAccessRepositoryType {
            get {
                return ResourceManager.GetString("InvaliOtherResourceSqlAccessRepositoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル結合はRDBMSリポジトリのみ可能です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvaliOtherResourceSqlAccessRepositoryType_Detail {
            get {
                return ResourceManager.GetString("InvaliOtherResourceSqlAccessRepositoryType_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   透過APIの設定が正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsTransparentApiIncorrect {
            get {
                return ResourceManager.GetString("IsTransparentApiIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ODataDeleteを実行しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItWasExecutedODataDelete {
            get {
                return ResourceManager.GetString("ItWasExecutedODataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyに一致する情報が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyMissMatch {
            get {
                return ResourceManager.GetString("KeyMissMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyに一致する情報が見つかりませんでした。対象のデータはすでに削除された可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyMissMatch_Detail {
            get {
                return ResourceManager.GetString("KeyMissMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyプロパティは、要求データに必要とされます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeyPropertyIsRequiredInRequestData {
            get {
                return ResourceManager.GetString("KeyPropertyIsRequiredInRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロギングRequestResponse接続が存在しないか、いっぱいです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingRequestResponseConnectionDoesNotExistOrIsFull {
            get {
                return ResourceManager.GetString("LoggingRequestResponseConnectionDoesNotExistOrIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   方法IPフィルタの例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MethodIPFilter {
            get {
                return ResourceManager.GetString("MethodIPFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Methodタイプが一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MethodTypeDoesNotMatch {
            get {
                return ResourceManager.GetString("MethodTypeDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストされたHttpメソッドタイプはサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MethodTypeDoesNotMatch_Detail {
            get {
                return ResourceManager.GetString("MethodTypeDoesNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MethodTypeが正しくありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MethodTypeIsIncorrect {
            get {
                return ResourceManager.GetString("MethodTypeIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリのキーがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MissingRepositoryKey {
            get {
                return ResourceManager.GetString("MissingRepositoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   規約に同意する必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MustAgreeToTheTerms {
            get {
                return ResourceManager.GetString("MustAgreeToTheTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に同意しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoAgreementAlreadyAgreement {
            get {
                return ResourceManager.GetString("NoAgreementAlreadyAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このユーザーは、指定された規約にはすでに同意しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoAgreementAlreadyAgreement_Detail {
            get {
                return ResourceManager.GetString("NoAgreementAlreadyAgreement_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新対象のデータがみつかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoRevokeNotAgreement {
            get {
                return ResourceManager.GetString("NoRevokeNotAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この規約には同意していないためリボークが行えません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoRevokeNotAgreement_Detail {
            get {
                return ResourceManager.GetString("NoRevokeNotAgreement_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意と承認がされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAgreedAndApproved {
            get {
                return ResourceManager.GetString("NotAgreedAndApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたのベンダーは、このリソースに対して同意をしていないか、または管理者が承認をしていないため、リソースを利用することができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAgreedAndApproved_Detail {
            get {
                return ResourceManager.GetString("NotAgreedAndApproved_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAgreementNoTerms {
            get {
                return ResourceManager.GetString("NotAgreementNoTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された規約が存在しないため同意できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAgreementNoTerms_Detail {
            get {
                return ResourceManager.GetString("NotAgreementNoTerms_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このAPIは、システムのために許可されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAllowedForSystem {
            get {
                return ResourceManager.GetString("NotAllowedForSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このAPIの使用は許可されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAllowedForSystem_Detail {
            get {
                return ResourceManager.GetString("NotAllowedForSystem_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認定アプリケーションの削除ができません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDeleteCertifiedApplicationNotMatch {
            get {
                return ResourceManager.GetString("NotDeleteCertifiedApplicationNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認定アプリケーションのキーが一致しないため、削除ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDeleteCertifiedApplicationNotMatch_Detail {
            get {
                return ResourceManager.GetString("NotDeleteCertifiedApplicationNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーで指定したものが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDeleteTermGroupKeyNotMatch {
            get {
                return ResourceManager.GetString("NotDeleteTermGroupKeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーで指定したものが見つかりません。規約グループの削除ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDeleteTermGroupKeyNotMatch_Detail {
            get {
                return ResourceManager.GetString("NotDeleteTermGroupKeyNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーで指定したものが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDeleteTermsKeyNotMatch {
            get {
                return ResourceManager.GetString("NotDeleteTermsKeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーで指定したものが見つかりません。規約プの削除ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDeleteTermsKeyNotMatch_Detail {
            get {
                return ResourceManager.GetString("NotDeleteTermsKeyNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーグループの削除ができません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDeleteUserGroupKeyNotMatch {
            get {
                return ResourceManager.GetString("NotDeleteUserGroupKeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーグループのキーが一致しないため、削除ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotDeleteUserGroupKeyNotMatch_Detail {
            get {
                return ResourceManager.GetString("NotDeleteUserGroupKeyNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実装されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedException {
            get {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロードされたファイルの位置と一致しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotMatchUploadedFilePosition {
            get {
                return ResourceManager.GetString("NotMatchUploadedFilePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV形式の例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotParseCsvException {
            get {
                return ResourceManager.GetString("NotParseCsvException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーで指定したものが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotUpdateTermGroupKeyNotMatch {
            get {
                return ResourceManager.GetString("NotUpdateTermGroupKeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーで指定したものが見つかりません。規約グループの更新ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotUpdateTermGroupKeyNotMatch_Detail {
            get {
                return ResourceManager.GetString("NotUpdateTermGroupKeyNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーで指定したものが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotUpdateTermsGKeyNotMatch {
            get {
                return ResourceManager.GetString("NotUpdateTermsGKeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーで指定したものが見つかりません。規約の更新ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotUpdateTermsGKeyNotMatch_Detail {
            get {
                return ResourceManager.GetString("NotUpdateTermsGKeyNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認定アプリケーションの登録ができません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoValidVendorOrSystem {
            get {
                return ResourceManager.GetString("NoValidVendorOrSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベンダーまたはシステムが有効でないため認定アプリケーションの登録ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoValidVendorOrSystem_Detail {
            get {
                return ResourceManager.GetString("NoValidVendorOrSystem_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Odataの例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataException {
            get {
                return ResourceManager.GetString("ODataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ODataPatchの更新対象がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataPatchNotFound {
            get {
                return ResourceManager.GetString("ODataPatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ODataPatchのリクエストが不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataPatchRequestInvalid {
            get {
                return ResourceManager.GetString("ODataPatchRequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加の検索条件が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataPatchRequestInvalid_AdditionalConditionInvalid {
            get {
                return ResourceManager.GetString("ODataPatchRequestInvalid_AdditionalConditionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストに更新不可のプロパティが含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataPatchRequestInvalid_UneditableProperty {
            get {
                return ResourceManager.GetString("ODataPatchRequestInvalid_UneditableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ODataPatchを利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataPatchUnavailable {
            get {
                return ResourceManager.GetString("ODataPatchUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ODataPatchを利用するにはODataPatchに対応したリポジトリを選択する必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataPatchUnavailable_NotSupportedRepository {
            get {
                return ResourceManager.GetString("ODataPatchUnavailable_NotSupportedRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   楽観排他が有効なAPIではODataPatchを利用できません。楽観排他を無効化してODataPatchを利用するにはX-NoOptimisticヘッダをtrueに設定してAPIを実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataPatchUnavailable_OptimisticConcurrencyEnabled {
            get {
                return ResourceManager.GetString("ODataPatchUnavailable_OptimisticConcurrencyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ひとつ以上の機能が有効なためODataPatchを利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ODataPatchUnavailable_UnsaportedFeaturesEnabled {
            get {
                return ResourceManager.GetString("ODataPatchUnavailable_UnsaportedFeaturesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OneOrMoreErrorsOccurred {
            get {
                return ResourceManager.GetString("OneOrMoreErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一つ以上のJSON検証エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OneOrMoreJsonValidationErrorsOccurred {
            get {
                return ResourceManager.GetString("OneOrMoreJsonValidationErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenIDが許可されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenidAccessControlAuthFailed_Detail {
            get {
                return ResourceManager.GetString("OpenidAccessControlAuthFailed_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenID認証のアクセストークンの期限切れ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdAccessTokenExpired {
            get {
                return ResourceManager.GetString("OpenIdAccessTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenID認証のアクセストークンの有効期限が切れています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdAccessTokenExpired_Detail {
            get {
                return ResourceManager.GetString("OpenIdAccessTokenExpired_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なOpenID認証のアクセストークン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdAccessTokenInvalid {
            get {
                return ResourceManager.GetString("OpenIdAccessTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenID認証に無効なアクセストークンが使われているか、または指定されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdAccessTokenInvalid_Detail {
            get {
                return ResourceManager.GetString("OpenIdAccessTokenInvalid_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenIDの認証が必要です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdAuthRequired {
            get {
                return ResourceManager.GetString("OpenIdAuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTTPヘッダー：AuthorizationにOpenID認証用のアクセストークンを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdAuthRequired_Detail {
            get {
                return ResourceManager.GetString("OpenIdAuthRequired_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このAPIは、認証局に許可されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdNotAllowedCA {
            get {
                return ResourceManager.GetString("OpenIdNotAllowedCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許可された認証局からOpenID認証用のアクセストークンを取得してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdNotAllowedCA_Detail {
            get {
                return ResourceManager.GetString("OpenIdNotAllowedCA_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenIDのユーザ操作例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIdUserOperationException {
            get {
                return ResourceManager.GetString("OpenIdUserOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API利用不可 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperatingVendorUserOnly {
            get {
                return ResourceManager.GetString("OperatingVendorUserOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このAPIを利用することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OperatingVendorUserOnly_Detail {
            get {
                return ResourceManager.GetString("OperatingVendorUserOnly_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queryの結果データがありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QueryResultsDidNotHaveData_ {
            get {
                return ResourceManager.GetString("QueryResultsDidNotHaveData.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Queryの構文に誤りがあります。{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuerySyntaxError {
            get {
                return ResourceManager.GetString("QuerySyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ構文エラー例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuerySyntaxErrorException {
            get {
                return ResourceManager.GetString("QuerySyntaxErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference,Notifyの更新失敗によるロールバックの失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReferenceFailureToRollBackDueToNotifyOfUpdateFilure {
            get {
                return ResourceManager.GetString("ReferenceFailureToRollBackDueToNotifyOfUpdateFilure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference,Notify機能による外部リソースに対し更新を行いました。ですが、外部リソースに対する更新に失敗したため、ロールバックを行おうとしましたが、失敗しました。ロールバックが必要な情報は下記になります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReferenceFailureToRollBackDueToNotifyOfUpdateFilure_Detail {
            get {
                return ResourceManager.GetString("ReferenceFailureToRollBackDueToNotifyOfUpdateFilure_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリキーが設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepositoryKeyHasNotBeenSet {
            get {
                return ResourceManager.GetString("RepositoryKeyHasNotBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リポジトリキーが設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepositoryKeyHasNotBeenSet_Detail {
            get {
                return ResourceManager.GetString("RepositoryKeyHasNotBeenSet_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストボディは、Arrayのみです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestBodyIsArrayOnly {
            get {
                return ResourceManager.GetString("RequestBodyIsArrayOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストボディは空です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestBodyIsEmpty {
            get {
                return ResourceManager.GetString("RequestBodyIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソースグループの削除ができません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceGroup_Delete_NotFound {
            get {
                return ResourceManager.GetString("ResourceGroup_Delete_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソースグループIDのデータが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceGroup_Delete_NotFound_Detail {
            get {
                return ResourceManager.GetString("ResourceGroup_Delete_NotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソースグループのデータがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceGroup_GetList_NotFound {
            get {
                return ResourceManager.GetString("ResourceGroup_GetList_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に該当するリソースグループのデータが取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceGroup_GetList_NotFound_Detail {
            get {
                return ResourceManager.GetString("ResourceGroup_GetList_NotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソースグループの登録ができません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceGroup_Register_NotFound {
            get {
                return ResourceManager.GetString("ResourceGroup_Register_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データが存在しないためです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceGroup_Register_NotFound_Detail {
            get {
                return ResourceManager.GetString("ResourceGroup_Register_NotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソースが公開されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceIsNotPublic {
            get {
                return ResourceManager.GetString("ResourceIsNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソーススキーマ適用エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   additionalPropertiesをtrueにすることはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_AllowAdditionalProperties {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_AllowAdditionalProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トップレベルのallOf/anyOf/oneOfは使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_CombiningSchemas {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_CombiningSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ名に使用できない文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_InvalidPropertyName {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_InvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既存のプロパティの削除及び型変更はできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_ModifyExistingProperties {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_ModifyExistingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_NoProperties {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_NoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1つ以上のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_OneOrMoreErrorsOccurred {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_OneOrMoreErrorsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ名が長すぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_PropertyNameTooLong {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_PropertyNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティのタイプは必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_PropertyTypeRequired {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_PropertyTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソーススキーマは必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_ResourceSchemaRequired {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_ResourceSchemaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティの数が多すぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResourceSchemaNotAdaptable_TooMatchProperties {
            get {
                return ResourceManager.GetString("ResourceSchemaNotAdaptable_TooMatchProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークのリソース削除が終了できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_RemoveResourceEnd_Fail {
            get {
                return ResourceManager.GetString("Revoke_RemoveResourceEnd_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークのリソース削除の終了は既にされています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_RemoveResourceEnd_Fail_Detail {
            get {
                return ResourceManager.GetString("Revoke_RemoveResourceEnd_Fail_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークのリソース削除が終了できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_RemoveResourceEnd_NotFound {
            get {
                return ResourceManager.GetString("Revoke_RemoveResourceEnd_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークのリソース削除の開始がおこなわれていないか、または、ユーザーの同意が記録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_RemoveResourceEnd_NotFound_Detail {
            get {
                return ResourceManager.GetString("Revoke_RemoveResourceEnd_NotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークのリソース削除が開始できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_RemoveResourceStart_Fail {
            get {
                return ResourceManager.GetString("Revoke_RemoveResourceStart_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ControllerIdまたはUserRevokeIdのIDが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_RemoveResourceStart_Fail_Detail {
            get {
                return ResourceManager.GetString("Revoke_RemoveResourceStart_Fail_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークのスタートが記録できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_Start_FK {
            get {
                return ResourceManager.GetString("Revoke_Start_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FKエラーです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_Start_FK_Detail {
            get {
                return ResourceManager.GetString("Revoke_Start_FK_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークのスタートが記録できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_Start_NotAgreement {
            get {
                return ResourceManager.GetString("Revoke_Start_NotAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意している規約がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_Start_NotAgreement_Detail {
            get {
                return ResourceManager.GetString("Revoke_Start_NotAgreement_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意していません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_Stop_NotAgreement {
            get {
                return ResourceManager.GetString("Revoke_Stop_NotAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意していないため、Stopの記録ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_Stop_NotAgreement_Detail {
            get {
                return ResourceManager.GetString("Revoke_Stop_NotAgreement_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意していません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_Stop_NotStart {
            get {
                return ResourceManager.GetString("Revoke_Stop_NotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リボークのスタートが記録されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Revoke_Stop_NotStart_Detail {
            get {
                return ResourceManager.GetString("Revoke_Stop_NotStart_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RoslynScriptRuntimeの例外が発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoslynScriptRuntimeException {
            get {
                return ResourceManager.GetString("RoslynScriptRuntimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sendMailTamplateCd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SendMailTamplateCd {
            get {
                return ResourceManager.GetString("SendMailTamplateCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLデータベース例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SqlDataBaseException {
            get {
                return ResourceManager.GetString("SqlDataBaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ODataの構文エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyntaxErrorOfOData {
            get {
                return ResourceManager.GetString("SyntaxErrorOfOData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ODataの構文が間違っているか、ODataの対応していない構文が使われています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyntaxErrorOfOData_Detail {
            get {
                return ResourceManager.GetString("SyntaxErrorOfOData_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   filterに不正な項目が指定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyntaxErrorOfOData_InvalidFilterColumn {
            get {
                return ResourceManager.GetString("SyntaxErrorOfOData_InvalidFilterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   filterに不正な値が指定されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyntaxErrorOfOData_InvalidFilterValue {
            get {
                return ResourceManager.GetString("SyntaxErrorOfOData_InvalidFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}はサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyntaxErrorOfOData_NotSupportedODataOperation {
            get {
                return ResourceManager.GetString("SyntaxErrorOfOData_NotSupportedODataOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   規約グループのデータはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TermGroupNotFound {
            get {
                return ResourceManager.GetString("TermGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に該当する規約グループのデータはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TermGroupNotFound_Detail {
            get {
                return ResourceManager.GetString("TermGroupNotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   規約のデータはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TermsNotFound {
            get {
                return ResourceManager.GetString("TermsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に該当する規約のデータはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TermsNotFound_Detail {
            get {
                return ResourceManager.GetString("TermsNotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このURLは、ドキュメントの履歴をサポートしていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThisURLDoesNotSupportDocumentHistory {
            get {
                return ResourceManager.GetString("ThisURLDoesNotSupportDocumentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenIdの認証に失敗しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToAuthenticateTheOpenIdHasFailed {
            get {
                return ResourceManager.GetString("ToAuthenticateTheOpenIdHasFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新対象のデータが複数見つかりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TooMachData {
            get {
                return ResourceManager.GetString("TooMachData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョンの種類は、intまたはGUIDです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeOfVersionIsIntOrGuid {
            get {
                return ResourceManager.GetString("TypeOfVersionIsIntOrGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新履歴が見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateHistoryNotFound {
            get {
                return ResourceManager.GetString("UpdateHistoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーグループのデータはありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserGroupNotFound {
            get {
                return ResourceManager.GetString("UserGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に該当するユーザーグループのデータはありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserGroupNotFound_Detail {
            get {
                return ResourceManager.GetString("UserGroupNotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ共有の削除ができません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserResourceShare_Delete_KeyNotMatch {
            get {
                return ResourceManager.GetString("UserResourceShare_Delete_KeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ共有のキーがマッチしないためデータ共有の削除ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserResourceShare_Delete_KeyNotMatch_Detail {
            get {
                return ResourceManager.GetString("UserResourceShare_Delete_KeyNotMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ共有のデータが取得できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserResourceShare_GetList_NotFound {
            get {
                return ResourceManager.GetString("UserResourceShare_GetList_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に該当するデータ共有のデータが取得できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserResourceShare_GetList_NotFound_Detail {
            get {
                return ResourceManager.GetString("UserResourceShare_GetList_NotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ共有の登録ができません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserResourceShare_Register_UnMatchKey {
            get {
                return ResourceManager.GetString("UserResourceShare_Register_UnMatchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ共有のキーがマッチしないためデータ共有の登録ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserResourceShare_Register_UnMatchKey_Detail {
            get {
                return ResourceManager.GetString("UserResourceShare_Register_UnMatchKey_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ共有の登録ができません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserResourceShare_Register_UserShareTypeCodeMissMatch {
            get {
                return ResourceManager.GetString("UserResourceShare_Register_UserShareTypeCodeMissMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   user_share_type_codeの値が不正なため、データ共有の登録ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserResourceShare_Register_UserShareTypeCodeMissMatch_Detail {
            get {
                return ResourceManager.GetString("UserResourceShare_Register_UserShareTypeCodeMissMatch_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同意一覧のデータはありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserTermsNotFound {
            get {
                return ResourceManager.GetString("UserTermsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に該当する同意一覧のデータはありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserTermsNotFound_Detail {
            get {
                return ResourceManager.GetString("UserTermsNotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベンダーやシステムが未指定です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorOrSystemUnspecified {
            get {
                return ResourceManager.GetString("VendorOrSystemUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AccessTokenIdがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorSystemAccessTokenIdMissing {
            get {
                return ResourceManager.GetString("VendorSystemAccessTokenIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VendorSystem AccessTokenが見つかりません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorSystemAccessTokenNotFound {
            get {
                return ResourceManager.GetString("VendorSystemAccessTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベンダーシステム認証用のアクセストークンを取得し直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorSystemAccessTokenNotFound_Detail {
            get {
                return ResourceManager.GetString("VendorSystemAccessTokenNotFound_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VendorSystem認証が必要です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorSystemAuthRequired {
            get {
                return ResourceManager.GetString("VendorSystemAuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTTPヘッダー：X-Authorizationにベンダーシステム認証用のアクセストークンを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorSystemAuthRequired_Detail {
            get {
                return ResourceManager.GetString("VendorSystemAuthRequired_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VendorSystem AccessTokenの有効期限が切れています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorSystemTokenExpired {
            get {
                return ResourceManager.GetString("VendorSystemTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VendorSystem AccessTokenが無効か、または、指定されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VendorSystemTokenInvalid {
            get {
                return ResourceManager.GetString("VendorSystemTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョンは、バージョン情報の中で存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionDoesNotExistInHistory {
            get {
                return ResourceManager.GetString("VersionDoesNotExistInHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョンが必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionIsRequired {
            get {
                return ResourceManager.GetString("VersionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gatewayを呼び出しましたがデータがありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WeCallTheGatewayDidNotHaveTheData {
            get {
                return ResourceManager.GetString("WeCallTheGatewayDidNotHaveTheData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   間違った内部呼び出しキーワード。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WrongInternalCallingKeyword {
            get {
                return ResourceManager.GetString("WrongInternalCallingKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X-UserResourceSharingを指定できるのはデータ取得のみです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string X_UserResourceSharingCanBeSpecifiedForDataRetrieval {
            get {
                return ResourceManager.GetString("X-UserResourceSharingCanBeSpecifiedForDataRetrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X-リファレンスヘッダーが無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XReferenceHeaderIsInvalid {
            get {
                return ResourceManager.GetString("XReferenceHeaderIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xversion NOTFOUND例外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XVersionNotFoundException {
            get {
                return ResourceManager.GetString("XVersionNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   利用できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YouCanNotUseIt {
            get {
                return ResourceManager.GetString("YouCanNotUseIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添付ファイル機能が有効になっていないため利用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YouCanNotUseIt_Detail {
            get {
                return ResourceManager.GetString("YouCanNotUseIt_Detail", resourceCulture);
            }
        }
    }
}
