using System.ComponentModel.DataAnnotations;

namespace JP.DataHub.ManageApi.Models
{
    public enum ScreenId
    {
        [ScreenIdName("トップ")]
        DI_002,
        [ScreenIdName("ベンダー")]
        DI_011,
        [ScreenIdName("システム")]
        DI_012,
        [ScreenIdName("ユーザ招待")]
        DI_013,
        [ScreenIdName("API")]
        DI_021,
        [ScreenIdName("メソッド")]
        DI_022,
        [ScreenIdName("モデル")]
        DI_023,
        [ScreenIdName("共有設定")]
        DI_024,
        [ScreenIdName("バッチステータス")]
        DI_030,
        [ScreenIdName("お知らせ")]
        DI_038,
        [ScreenIdName("ドキュメントダウンロード")]
        DI_039,
        [ScreenIdName("IPフィルタグループ")]
        DI_040,
        [ScreenIdName("権限")]
        DI_041,
        [ScreenIdName("ベンダーリポジトリグループ")]
        DI_042,
        [ScreenIdName("ドキュメントアップロード")]
        DI_045,
        [ScreenIdName("規約")]
        DI_046,
        [ScreenIdName("ETLスクリプト実行")]
        DI_047,
        [ScreenIdName("スクリプト定期実行")]
        DI_048,
        [ScreenIdName("添付ファイル一覧")]
        DI_049,
        [ScreenIdName("Admin認証設定")]
        DI_050,
        [ScreenIdName("リポジトリグループ")]
        DI_051,
        [ScreenIdName("ダッシュボード設定一覧")]
        DI_060,
        [ScreenIdName("ダッシュボード")]
        DI_061,
        [ScreenIdName("ダッシュボード使用データ")]
        DI_070,
        [ScreenIdName("ダッシュボード提供データ")]
        DI_071,
        [ScreenIdName("ダッシュボード管理データ")]
        DI_072,
        [ScreenIdName("証跡-管理画面")]
        DI_080,
        [ScreenIdName("メールテンプレート")]
        DI_090,
        [ScreenIdName("APIメールテンプレート設定")]
        DI_091,
        [ScreenIdName("Webhook")]
        DI_100,
        [ScreenIdName("CSVインポート")]
        DI_110,
        [ScreenIdName("CSVエクスポート")]
        DI_111
    }
}
